# Add 'documentation' label to any changes within docs folders or root md files
documentation:
- docs/**/*
- "*.md"

# Add 'frontend' label to any changes in src/ui or similar folders (example)
frontend:
- src/ui/**/*
- src/components/**/*
- src/styles/**/*

# Add 'backend' label
backend:
- src/api/**/*
- src/db/**/*
- src/services/**/*

# Add 'tests' label
tests:
- tests/**/*
- "**/*.test.js"
- "**/*.spec.js"
