documentation:
- 'docs/**/*'
- '*.md'

frontend:
- 'src/ui/**/*'
- 'src/components/**/*'
- 'src/styles/**/*'

backend:
- 'src/api/**/*'
- 'src/db/**/*'
- 'src/services/**/*'

tests:
- 'tests/**/*'
- '**/*.test.js'
- '**/*.spec.js'
